# =============================================================================
# run_jtag.tcl — Week 6
# XSCT script: load and run run_bitlinear_standalone.elf on ZCU106 via JTAG
#
# Usage (from fpga_erven/ps_host/):
#   xsct run_jtag.tcl
#
# Prerequisites:
#   1. hw_server running (Vivado Hardware Manager open, or: hw_server &)
#   2. ZCU106 powered on and JTAG connected
#   3. Bitstream already programmed (done earlier with Vivado)
#   4. Application ELF built:
#      fpga_erven/ps_host/vitis_ws/bitlinear_app/Debug/bitlinear_app.elf
#
# UART output:
#   Open a second terminal before running this script:
#   sudo picocom -b 115200 /dev/ttyUSB2
# =============================================================================

# ---- Configuration ----------------------------------------------------------
set HW_SERVER_URL  "tcp:localhost:3121"
set ELF_PATH       "./vitis_ws/bitlinear_app/Debug/bitlinear_app.elf"
set PSU_INIT_TCL   "./vitis_ws/zcu106_platform/hw/psu_init.tcl"
# -----------------------------------------------------------------------------

puts "\n>>> Connecting to hw_server at $HW_SERVER_URL ..."
connect -url $HW_SERVER_URL

# List all targets for verification
puts ">>> Available targets:"
targets

# Select the APU Cortex-A53 #0
puts "\n>>> Selecting Cortex-A53 #0 ..."
targets -set -nocase -filter {name =~ "Cortex-A53 #0"}

# ---- PS Initialisation -------------------------------------------------------
# psu_init configures PS clocks, DDR controller, MIO, etc.
# Without it, the standalone app cannot access DDR or peripherals.
# The psu_init.tcl is generated by Vitis when creating the platform from XSA.
puts ">>> Initialising PS (psu_init) ..."
if {[file exists $PSU_INIT_TCL]} {
    source $PSU_INIT_TCL
    psu_init
    puts ">>> PS init done."
} else {
    puts "WARNING: $PSU_INIT_TCL not found."
    puts "         Build the Vitis platform first (step 3 in setup instructions)."
    puts "         Attempting to continue — may fail if DDR is not initialised."
}

# ---- Optional: re-program bitstream ------------------------------------------
# Not needed if already programmed via Vivado Hardware Manager.
# Uncomment if you want this script to be fully self-contained:
#
# set BIT_PATH "../../vitis_project/bitlinear_system/bitlinear_system.runs/impl_1/bitlinear_system_wrapper.bit"
# puts ">>> Programming bitstream ..."
# targets -set -nocase -filter {name =~ "xczu7_0"}
# fpga $BIT_PATH
# targets -set -nocase -filter {name =~ "Cortex-A53 #0"}

# ---- Load and run ------------------------------------------------------------
puts ">>> Resetting processor ..."
rst -processor

puts ">>> Downloading ELF: $ELF_PATH ..."
if {![file exists $ELF_PATH]} {
    puts "ERROR: ELF not found at $ELF_PATH"
    puts "       Build the Vitis application first (step 4 in setup instructions)."
    exit 1
}
dow $ELF_PATH

puts ">>> Running application ..."
puts "    (UART output on /dev/ttyUSB2 at 115200 baud)"
puts "    (Ctrl+C here to stop XSCT; board keeps running)"
con

puts "\n>>> Application started. Waiting for completion ..."
puts "    Watch the picocom terminal for results."
puts "    Press Ctrl+C to detach XSCT (application continues on board)."

# Optional: wait for execution to finish by polling a breakpoint
# Uncomment to have XSCT block until main() returns:
# bpadd -addr &exit
# con
# bpremove -all
