// =============================================================================
// run_bitlinear.cpp — Week 6
// PS Host Program — BitLinear-FPGA Alpha
// Student : Erven LE BIVIC — Seoul National University
// =============================================================================
//
// Runs the BitLinear HLS IP on the ZCU106 board and compares the FPGA output
// against the golden reference binary test vectors from Week 2.
//
// Prerequisites
// -------------
//   - Bitstream programmed (JTAG or SD card)
//   - XSA / device tree booted with correct address map
//   - Binary test vectors available at TV_BASE_PATH
//   - Run as root (required for /dev/mem and /proc/self/pagemap PFN reads)
//
// Usage
// -----
//   g++ -O2 -o run_bitlinear run_bitlinear.cpp
//   sudo ./run_bitlinear [path/to/reference/test_vectors]
//
// AXI address map — UPDATE AFTER VIVADO ADDRESS EDITOR
// -----------------------------------------------------
//   Open Vivado → Block Design → Address Editor after block design is complete.
//   Replace the two placeholder values below with the actual assigned offsets.
//
//   CTRL_PHYS_BASE    → s_axi_CTRL    (ap_start/done, M, K)
//   CONTROL_PHYS_BASE → s_axi_control (x, W_packed, y base addresses)
//
// Register map (from xbitlinear_hls_hw.h, do not edit)
// -----------------------------------------------------
//   s_axi_CTRL:
//     0x00  ap_ctrl   bit0=ap_start, bit1=ap_done, bit2=ap_idle
//     0x10  M         (scalar, 32-bit)
//     0x18  K         (scalar, 32-bit)
//   s_axi_control:
//     0x10  x_lo      x[] physical address [31:0]
//     0x14  x_hi      x[] physical address [63:32]
//     0x1C  W_lo      W_packed[] physical address [31:0]
//     0x20  W_hi      W_packed[] physical address [63:32]
//     0x28  y_lo      y[] physical address [31:0]
//     0x2C  y_hi      y[] physical address [63:32]
// =============================================================================

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <cassert>

#include <errno.h>
#include <fcntl.h>
#include <sys/mman.h>
#include <sys/types.h>
#include <time.h>
#include <unistd.h>

// =============================================================================
// AXI base addresses — FILL FROM VIVADO ADDRESS EDITOR BEFORE RUNNING
// =============================================================================
// These are the physical addresses of the two AXI-Lite slave interfaces
// as assigned by Vivado. Default range is 0xA0000000–0xAFFFFFFF for ZCU106 PL.

#define CTRL_PHYS_BASE     0xA0000000ULL   // s_axi_CTRL  — TBD: check Vivado addr editor
#define CONTROL_PHYS_BASE  0xA0010000ULL   // s_axi_control — TBD: check Vivado addr editor
#define AXILITE_MAP_SIZE   0x10000UL       // 64 KB per interface

// =============================================================================
// Register offsets (from xbitlinear_hls_hw.h — generated by Vitis HLS)
// =============================================================================

// s_axi_CTRL register offsets
#define CTRL_AP_CTRL   0x00
#define CTRL_M_DATA    0x10
#define CTRL_K_DATA    0x18

// ap_ctrl bit positions
#define AP_START_BIT   (1U << 0)
#define AP_DONE_BIT    (1U << 1)
#define AP_IDLE_BIT    (1U << 2)

// s_axi_control register offsets (pointer arguments)
#define CTL_X_LO       0x10
#define CTL_X_HI       0x14
#define CTL_W_LO       0x1C
#define CTL_W_HI       0x20
#define CTL_Y_LO       0x28
#define CTL_Y_HI       0x2C

// =============================================================================
// DMA buffer layout
// =============================================================================
// All three buffers are allocated as a single contiguous page-aligned block
// to guarantee they land in physically contiguous pages with a single mlock.
// Sizes are set to the HLS depth pragmas (worst-case: 512-element x, 256K-byte W).

#define MAX_M           512
#define MAX_K           1024
#define MAX_PACKED_SZ   (MAX_M * MAX_K / 4)  // = 131 072 bytes

// Layout within the single DMA allocation:
//   [0 .. MAX_K-1]                     : x_buf   (int8_t, MAX_K bytes)
//   [MAX_K .. MAX_K + MAX_PACKED_SZ-1] : W_buf   (uint8_t, MAX_PACKED_SZ bytes)
//   aligned to next page               : y_buf   (int32_t, MAX_M * 4 bytes)

#define X_OFFSET        0
#define W_OFFSET        (MAX_K)
#define Y_OFFSET        ((MAX_K + MAX_PACKED_SZ + 4095) & ~4095UL)
#define DMA_TOTAL_SIZE  (Y_OFFSET + MAX_M * sizeof(int32_t))

// =============================================================================
// Poll timeout
// =============================================================================
#define POLL_TIMEOUT_MS   5000   // 5 seconds

// =============================================================================
// Test vector directory (overridable via argv[1])
// =============================================================================
static const char *TV_DEFAULT_PATH = "../../reference/test_vectors";

// Test vector subdirectory names (Week 2 canonical set)
static const char *TV_DIRS[] = {
    "test01_random",
    "test02_W_zero",
    "test03_W_plus1",
    "test04_W_minus1",
    "test05_sparse",
    "test06_dense",
    "test07_xmax",
    "test08_xmin",
    "test09_manual",
    "test10_large",
    NULL
};

// =============================================================================
// Section 1 — Low-level register helpers
// =============================================================================

static inline void reg_write32(volatile uint8_t *base, uint32_t offset, uint32_t val) {
    *reinterpret_cast<volatile uint32_t *>(base + offset) = val;
    // Ensure the write reaches the AXI fabric before returning
    __sync_synchronize();
}

static inline uint32_t reg_read32(volatile uint8_t *base, uint32_t offset) {
    __sync_synchronize();
    return *reinterpret_cast<volatile uint32_t *>(base + offset);
}

// =============================================================================
// Section 2 — /dev/mem mapping
// =============================================================================

static int g_devmem_fd = -1;

static int open_devmem(void) {
    g_devmem_fd = open("/dev/mem", O_RDWR | O_SYNC);
    if (g_devmem_fd < 0) {
        perror("[error] open /dev/mem");
        fprintf(stderr, "       Make sure you are running as root.\n");
    }
    return g_devmem_fd;
}

static volatile uint8_t *mmap_phys(uint64_t phys_addr, size_t size) {
    void *ptr = mmap(nullptr, size, PROT_READ | PROT_WRITE, MAP_SHARED,
                     g_devmem_fd, static_cast<off_t>(phys_addr));
    if (ptr == MAP_FAILED) {
        fprintf(stderr, "[error] mmap 0x%llx (%zu bytes): %s\n",
                (unsigned long long)phys_addr, size, strerror(errno));
        return nullptr;
    }
    return reinterpret_cast<volatile uint8_t *>(ptr);
}

// =============================================================================
// Section 3 — Virtual-to-physical address translation
// =============================================================================
// Reads /proc/self/pagemap to find the physical frame number (PFN) of a
// virtual page. Requires root on Linux >= 4.0.
//
// After posix_memalign + mlock, every page is guaranteed to be present and
// pinned, so this translation is stable for the lifetime of the process.

static uint64_t virt_to_phys(const void *vaddr) {
    static const long page_size = sysconf(_SC_PAGESIZE);
    FILE *pm = fopen("/proc/self/pagemap", "rb");
    if (!pm) {
        perror("[error] fopen /proc/self/pagemap");
        return 0;
    }

    uintptr_t va      = reinterpret_cast<uintptr_t>(vaddr);
    uint64_t  page_n  = va / static_cast<uint64_t>(page_size);
    uint64_t  pg_off  = va % static_cast<uint64_t>(page_size);

    if (fseek(pm, static_cast<long>(page_n * 8), SEEK_SET) != 0) {
        perror("[error] fseek pagemap");
        fclose(pm);
        return 0;
    }

    uint64_t entry = 0;
    if (fread(&entry, sizeof(entry), 1, pm) != 1) {
        fprintf(stderr, "[error] fread pagemap entry\n");
        fclose(pm);
        return 0;
    }
    fclose(pm);

    if (!(entry & (1ULL << 63))) {
        fprintf(stderr, "[error] page not present for vaddr 0x%lx\n", va);
        return 0;
    }

    uint64_t pfn = entry & 0x7FFFFFFFFFFFFFULL;
    return (pfn * static_cast<uint64_t>(page_size)) + pg_off;
}

// =============================================================================
// Section 4 — Data-cache maintenance (ARM64)
// =============================================================================
// The PS HP ports bypass the ARM L1/L2 caches. We must flush before the PL
// reads (MEM_IN, MEM_W) and invalidate before the PS reads back the result
// (MEM_OUT). These instructions are accessible from EL0 on Linux >= 4.4 with
// SCTLR_EL1.UCI set (enabled by default in Petalinux / mainline ARM64 kernel).

static void dcache_flush_range(const void *addr, size_t len) {
    // DC CIVAC: Clean and Invalidate to Point of Coherency
    uintptr_t start = reinterpret_cast<uintptr_t>(addr) & ~63UL;
    uintptr_t end   = (reinterpret_cast<uintptr_t>(addr) + len + 63) & ~63UL;
    for (uintptr_t a = start; a < end; a += 64)
        asm volatile("dc civac, %0" :: "r"(a) : "memory");
    asm volatile("dsb sy" ::: "memory");
    asm volatile("isb"    ::: "memory");
}

static void dcache_invalidate_range(const void *addr, size_t len) {
    // DC IVAC: Invalidate to Point of Coherency
    asm volatile("dsb sy" ::: "memory");
    uintptr_t start = reinterpret_cast<uintptr_t>(addr) & ~63UL;
    uintptr_t end   = (reinterpret_cast<uintptr_t>(addr) + len + 63) & ~63UL;
    for (uintptr_t a = start; a < end; a += 64)
        asm volatile("dc ivac, %0" :: "r"(a) : "memory");
    asm volatile("dsb sy" ::: "memory");
}

// =============================================================================
// Section 5 — Inline CPU golden reference
// =============================================================================
// Replicates the exact computation of bitlinear_hls.cpp using the same packed
// weight format (flat index m*K+k, LSB-first 2-bit codes).
// Used to double-check the expected_output_int32.bin against a live CPU run.

static inline int8_t decode_weight_inline(uint8_t byte, int pos) {
    uint8_t code = (byte >> (pos * 2)) & 0x3;
    return (code == 1) ? 1 : (code == 2) ? -1 : 0;
}

static void cpu_bitlinear_ref(
    const int8_t  *x,
    const uint8_t *W_packed,
    int32_t       *y,
    int            M,
    int            K)
{
    for (int m = 0; m < M; ++m) {
        int32_t acc = 0;
        for (int k = 0; k < K; ++k) {
            int flat = m * K + k;
            int8_t w = decode_weight_inline(W_packed[flat / 4], flat % 4);
            acc += w * static_cast<int32_t>(x[k]);
        }
        y[m] = acc;
    }
}

// =============================================================================
// Section 6 — Binary file helpers
// =============================================================================

static size_t load_bin(const char *path, void *dst, size_t max_bytes) {
    FILE *f = fopen(path, "rb");
    if (!f) {
        fprintf(stderr, "[error] cannot open: %s\n", path);
        return 0;
    }
    fseek(f, 0, SEEK_END);
    size_t sz = static_cast<size_t>(ftell(f));
    rewind(f);
    if (sz > max_bytes) {
        fprintf(stderr, "[error] %s: file too large (%zu > %zu)\n", path, sz, max_bytes);
        fclose(f);
        return 0;
    }
    size_t rd = fread(dst, 1, sz, f);
    fclose(f);
    if (rd != sz) {
        fprintf(stderr, "[error] short read on %s\n", path);
        return 0;
    }
    return sz;
}

// =============================================================================
// Section 7 — IP control (start / poll done)
// =============================================================================

static void ip_write_args(
    volatile uint8_t *ctrl_reg,
    volatile uint8_t *control_reg,
    uint64_t          phys_x,
    uint64_t          phys_W,
    uint64_t          phys_y,
    int               M,
    int               K)
{
    // Scalars (s_axi_CTRL)
    reg_write32(ctrl_reg, CTRL_M_DATA, static_cast<uint32_t>(M));
    reg_write32(ctrl_reg, CTRL_K_DATA, static_cast<uint32_t>(K));

    // Pointer registers (s_axi_control) — 64-bit split into lo/hi
    reg_write32(control_reg, CTL_X_LO, static_cast<uint32_t>(phys_x));
    reg_write32(control_reg, CTL_X_HI, static_cast<uint32_t>(phys_x >> 32));
    reg_write32(control_reg, CTL_W_LO, static_cast<uint32_t>(phys_W));
    reg_write32(control_reg, CTL_W_HI, static_cast<uint32_t>(phys_W >> 32));
    reg_write32(control_reg, CTL_Y_LO, static_cast<uint32_t>(phys_y));
    reg_write32(control_reg, CTL_Y_HI, static_cast<uint32_t>(phys_y >> 32));
}

// Returns elapsed nanoseconds, or -1 on timeout.
static long long ip_start_and_wait(volatile uint8_t *ctrl_reg) {
    struct timespec t0, t1;
    clock_gettime(CLOCK_MONOTONIC, &t0);

    // Assert ap_start (bit 0). The HLS ap_ctrl_hs protocol clears it automatically
    // (COH = Clear on Handshake) once the IP accepts the start.
    reg_write32(ctrl_reg, CTRL_AP_CTRL, AP_START_BIT);

    // Poll ap_done (bit 1) with timeout
    const long long timeout_ns = (long long)POLL_TIMEOUT_MS * 1000000LL;
    while (true) {
        clock_gettime(CLOCK_MONOTONIC, &t1);
        long long elapsed = (t1.tv_sec - t0.tv_sec) * 1000000000LL
                          + (t1.tv_nsec - t0.tv_nsec);
        if (reg_read32(ctrl_reg, CTRL_AP_CTRL) & AP_DONE_BIT)
            return elapsed;
        if (elapsed > timeout_ns) {
            fprintf(stderr, "[error] ap_done timeout after %d ms\n", POLL_TIMEOUT_MS);
            return -1;
        }
    }
}

// =============================================================================
// Section 8 — Single test-vector run
// =============================================================================

struct TestResult {
    bool     passed;
    int      mismatches;
    long long latency_ns;
    int      M;
    int      K;
};

static TestResult run_one_test(
    const char       *tv_dir,
    volatile uint8_t *ctrl_reg,
    volatile uint8_t *control_reg,
    uint8_t          *dma_buf,        // pinned DMA allocation
    uint64_t          dma_phys_base)  // physical base of dma_buf
{
    TestResult res = {};

    // ---------- Build file paths ----------
    char path_x[512], path_W[512], path_y_ref[512];
    snprintf(path_x,     sizeof(path_x),     "%s/activation_int8.bin",          tv_dir);
    snprintf(path_W,     sizeof(path_W),     "%s/weight_ternary_packed_2bit.bin", tv_dir);
    snprintf(path_y_ref, sizeof(path_y_ref), "%s/expected_output_int32.bin",     tv_dir);

    // ---------- Pointers into DMA buffer ----------
    int8_t   *x_buf  = reinterpret_cast<int8_t  *>(dma_buf + X_OFFSET);
    uint8_t  *W_buf  = dma_buf + W_OFFSET;
    int32_t  *y_fpga = reinterpret_cast<int32_t *>(dma_buf + Y_OFFSET);

    uint64_t phys_x  = dma_phys_base + X_OFFSET;
    uint64_t phys_W  = dma_phys_base + W_OFFSET;
    uint64_t phys_y  = dma_phys_base + Y_OFFSET;

    // ---------- Load activations ----------
    size_t x_bytes = load_bin(path_x, x_buf, MAX_K);
    if (!x_bytes) return res;
    int K = static_cast<int>(x_bytes);   // one byte per int8 element

    // ---------- Load packed weights ----------
    size_t W_bytes = load_bin(path_W, W_buf, MAX_PACKED_SZ);
    if (!W_bytes) return res;

    // Infer M from packed size: W_bytes = ceil(M*K/4)
    int M = static_cast<int>((W_bytes * 4) / static_cast<size_t>(K));

    res.M = M;
    res.K = K;

    // ---------- Load golden reference ----------
    int32_t y_ref[MAX_M] = {};
    size_t y_ref_bytes = load_bin(path_y_ref, y_ref, sizeof(y_ref));
    if (!y_ref_bytes) return res;
    if (y_ref_bytes != static_cast<size_t>(M) * sizeof(int32_t)) {
        fprintf(stderr, "[error] unexpected y_ref size: %zu bytes (expected %zu)\n",
                y_ref_bytes, static_cast<size_t>(M) * sizeof(int32_t));
        return res;
    }

    // Verify golden reference against inline CPU reference
    int32_t y_cpu[MAX_M] = {};
    cpu_bitlinear_ref(x_buf, W_buf, y_cpu, M, K);
    for (int m = 0; m < M; ++m) {
        if (y_cpu[m] != y_ref[m]) {
            fprintf(stderr, "[warn] CPU ref mismatch at m=%d: got %d expected %d\n",
                    m, y_cpu[m], y_ref[m]);
        }
    }

    // ---------- Clear output buffer ----------
    memset(y_fpga, 0, M * sizeof(int32_t));

    // ---------- Flush caches before PL reads ----------
    dcache_flush_range(x_buf, static_cast<size_t>(K));
    dcache_flush_range(W_buf, W_bytes);
    dcache_flush_range(y_fpga, static_cast<size_t>(M) * sizeof(int32_t));

    // ---------- Program IP and start ----------
    ip_write_args(ctrl_reg, control_reg, phys_x, phys_W, phys_y, M, K);

    long long lat_ns = ip_start_and_wait(ctrl_reg);
    if (lat_ns < 0) return res;
    res.latency_ns = lat_ns;

    // ---------- Invalidate cache so CPU reads PL-written y ----------
    dcache_invalidate_range(y_fpga, static_cast<size_t>(M) * sizeof(int32_t));

    // ---------- Compare FPGA output vs golden reference ----------
    int mismatches = 0;
    for (int m = 0; m < M; ++m) {
        if (y_fpga[m] != y_ref[m]) {
            if (mismatches < 5)   // print only the first 5 mismatches
                fprintf(stderr, "  [mismatch] m=%-4d  fpga=%d  ref=%d\n",
                        m, y_fpga[m], y_ref[m]);
            ++mismatches;
        }
    }
    res.mismatches = mismatches;
    res.passed     = (mismatches == 0);
    return res;
}

// =============================================================================
// Section 9 — Main
// =============================================================================

int main(int argc, char *argv[]) {
    const char *tv_base = (argc > 1) ? argv[1] : TV_DEFAULT_PATH;

    printf("=================================================================\n");
    printf("  BitLinear-FPGA Alpha — ZCU106 Board Execution\n");
    printf("  Week 6 — PS Host Program\n");
    printf("=================================================================\n");
    printf("  AXI CTRL     : 0x%016llX\n", (unsigned long long)CTRL_PHYS_BASE);
    printf("  AXI control  : 0x%016llX\n", (unsigned long long)CONTROL_PHYS_BASE);
    printf("  Test vectors : %s\n", tv_base);
    printf("-----------------------------------------------------------------\n\n");

    // -------------------------------------------------------------------------
    // Step 1: Open /dev/mem and map both AXI-Lite interfaces
    // -------------------------------------------------------------------------
    if (open_devmem() < 0) return 1;

    volatile uint8_t *ctrl_reg = mmap_phys(CTRL_PHYS_BASE, AXILITE_MAP_SIZE);
    if (!ctrl_reg) return 1;

    volatile uint8_t *control_reg = mmap_phys(CONTROL_PHYS_BASE, AXILITE_MAP_SIZE);
    if (!control_reg) return 1;

    // Verify IP is idle before proceeding
    uint32_t ap_status = reg_read32(ctrl_reg, CTRL_AP_CTRL);
    if (!(ap_status & AP_IDLE_BIT)) {
        fprintf(stderr, "[warn] IP not idle at startup (ap_ctrl = 0x%08X). "
                "Proceeding anyway — bitstream may need reprogramming.\n", ap_status);
    } else {
        printf("[ok] IP is idle (ap_ctrl = 0x%08X)\n\n", ap_status);
    }

    // -------------------------------------------------------------------------
    // Step 2: Allocate pinned DMA buffer
    // -------------------------------------------------------------------------
    // Single contiguous allocation covering x, W_packed, and y.
    // mlock prevents swapping; /proc/self/pagemap gives the physical address.
    void *raw = nullptr;
    if (posix_memalign(&raw, 4096, DMA_TOTAL_SIZE) != 0) {
        perror("[error] posix_memalign");
        return 1;
    }
    // Touch every page to force allocation before mlock
    memset(raw, 0, DMA_TOTAL_SIZE);

    if (mlock(raw, DMA_TOTAL_SIZE) != 0) {
        perror("[error] mlock — check /proc/sys/vm/max_map_count and RLIMIT_MEMLOCK");
        return 1;
    }

    uint8_t *dma_buf = reinterpret_cast<uint8_t *>(raw);

    // Translate virtual base to physical
    uint64_t dma_phys_base = virt_to_phys(dma_buf);
    if (!dma_phys_base) {
        fprintf(stderr, "[error] VA→PA translation failed. "
                "Ensure /proc/self/pagemap PFN access is enabled (run as root).\n");
        return 1;
    }
    printf("[ok] DMA buffer: VA=0x%lX  PA=0x%llX  size=%zu KB\n\n",
           reinterpret_cast<uintptr_t>(dma_buf),
           (unsigned long long)dma_phys_base,
           DMA_TOTAL_SIZE / 1024);

    // -------------------------------------------------------------------------
    // Step 3: Run all test vectors
    // -------------------------------------------------------------------------
    int total   = 0;
    int passed  = 0;
    long long total_lat_ns = 0;

    printf("%-25s  %5s  %5s  %9s  %s\n",
           "Test", "M", "K", "Lat (µs)", "Result");
    printf("%-25s  %5s  %5s  %9s  %s\n",
           "-------------------------", "-----", "-----", "---------", "------");

    for (int i = 0; TV_DIRS[i] != nullptr; ++i) {
        char tv_dir[512];
        snprintf(tv_dir, sizeof(tv_dir), "%s/%s", tv_base, TV_DIRS[i]);

        TestResult res = run_one_test(
            tv_dir, ctrl_reg, control_reg, dma_buf, dma_phys_base);

        ++total;
        if (res.passed) ++passed;
        total_lat_ns += res.latency_ns;

        double lat_us = static_cast<double>(res.latency_ns) / 1e3;

        printf("%-25s  %5d  %5d  %9.1f  %s\n",
               TV_DIRS[i], res.M, res.K, lat_us,
               res.passed ? "PASS ✓"
               : (res.latency_ns < 0 ? "TIMEOUT ✗"
                                     : "FAIL ✗"));

        if (!res.passed && res.mismatches > 0)
            fprintf(stderr, "  → %d mismatch(es) in %s\n", res.mismatches, TV_DIRS[i]);
    }

    // -------------------------------------------------------------------------
    // Step 4: Summary
    // -------------------------------------------------------------------------
    printf("\n=================================================================\n");
    printf("  RESULT : %d / %d PASS\n", passed, total);
    printf("  Total kernel time : %.1f µs  (sum over %d runs)\n",
           static_cast<double>(total_lat_ns) / 1e3, total);
    if (total > 0)
        printf("  Average per run   : %.1f µs\n",
               static_cast<double>(total_lat_ns) / static_cast<double>(total) / 1e3);
    printf("=================================================================\n");

    if (passed == total) {
        printf("\n[SUCCESS] FPGA output == CPU reference on all %d test vectors.\n", total);
    } else {
        fprintf(stderr, "\n[FAILURE] %d test(s) did not match the reference.\n",
                total - passed);
        fprintf(stderr, "  Check: AXI addresses, bitstream, cache coherency, VA→PA map.\n");
    }

    // -------------------------------------------------------------------------
    // Cleanup
    // -------------------------------------------------------------------------
    munlock(raw, DMA_TOTAL_SIZE);
    free(raw);
    munmap(const_cast<uint8_t *>(const_cast<uint8_t *>(
           reinterpret_cast<const uint8_t *>(ctrl_reg))), AXILITE_MAP_SIZE);
    munmap(const_cast<uint8_t *>(
           reinterpret_cast<const uint8_t *>(control_reg)), AXILITE_MAP_SIZE);
    close(g_devmem_fd);

    return (passed == total) ? 0 : 1;
}
