# =============================================================================
# run_hls.tcl
# Vitis HLS Script — BitLinear-FPGA Alpha
# =============================================================================
#
# Usage (from fpga_erven/hls/bitlinear/):
#   /tools/Xilinx/2025.1/Vitis/bin/vitis-run --mode hls --tcl run_hls.tcl
#
# This script runs the complete HLS flow:
#   Step 0 — Project setup
#   Step 1 — C Simulation       (testbench_cosim_vectors.cpp vs Week 2 .bin)
#   Step 2 — Synthesis          (II=1, Fmax ~137 MHz on xczu7ev)
#   Step 3 — RTL Co-Simulation  (XSim Verilog, 10/10 PASS proven)
#   Step 4 — IP Export          (Vivado ip_catalog format)
#
# Validated results (Week 5):
#   Synthesis  : II=1, Fmax 136.99 MHz, 0 DSP, 1% LUT, 1% BRAM
#   Co-sim     : 10/10 PASS — RTL output matches Week 2 Python reference
#   IP archive : llmcore_hls_bitlinear_hls_1_0.zip
# =============================================================================

set project_name  "bitlinear_hls_project"
set top_function  "bitlinear_hls"
set part          "xczu7ev-ffvc1156-2-e"
set clock_period  "10"

# =============================================================================
# Step 0 — Project setup
# =============================================================================

# Compute absolute path to reference/test_vectors/ for the co-sim testbench.
# TV_BASE_PATH is written to tv_path_generated.h (auto-generated, not committed).
# [pwd] must be fpga_erven/hls/bitlinear/ when this script is launched.
set tv_path [file normalize [file join [pwd] "../../../reference/test_vectors"]]

if {![file isdirectory $tv_path]} {
    puts "ERROR: test_vectors not found at: $tv_path"
    puts "       Run this script from fpga_erven/hls/bitlinear/"
    exit 1
}

# Write tv_path_generated.h so testbench_cosim_vectors.cpp can open .bin files
set hdr [open [file join [pwd] "tv_path_generated.h"] w]
puts $hdr "/* Auto-generated by run_hls.tcl — do not edit, not committed */"
puts $hdr "#ifndef TV_PATH_GENERATED_H"
puts $hdr "#define TV_PATH_GENERATED_H"
puts $hdr "#define TV_BASE_PATH \"$tv_path\""
puts $hdr "#endif"
close $hdr
puts ">>> TV_BASE_PATH = $tv_path"

open_project -reset $project_name
set_top $top_function

# Design files (kernel only — packing files are testbench utilities, not synthesised)
add_files bitlinear_hls.cpp
add_files bitlinear_hls.h

# Testbench files
# testbench_cosim_vectors.cpp: co-sim compatible, loads real Week 2 .bin test vectors
# Validates full chain: Python(S2) -> .bin -> C++ ref -> HLS csim -> RTL
add_files -tb testbench_cosim_vectors.cpp
add_files -tb tv_path_generated.h
add_files -tb ../packing/pack_ternary_2bit.cpp
add_files -tb ../packing/pack_ternary_2bit.h
add_files -tb ../packing/unpack_ternary_2bit.cpp

open_solution -reset "solution1"
set_part $part
create_clock -period $clock_period -name default

# =============================================================================
# Step 1 — C Simulation
# =============================================================================
puts ""
puts ">>> Step 1: C Simulation..."
csim_design -clean
puts ">>> C Simulation done."

# =============================================================================
# Step 2 — Synthesis
# =============================================================================
puts ""
puts ">>> Step 2: Synthesis..."
csynth_design
puts ">>> Synthesis done. Expected: II=1, Fmax ~137 MHz, 0 DSP."

# =============================================================================
# Step 3 — RTL Co-Simulation (XSim)
# Runs testbench_cosim_vectors.cpp against the generated Verilog.
# Validates: RTL output == Week 2 Python reference on all 10 test vectors.
# =============================================================================
puts ""
puts ">>> Step 3: RTL Co-Simulation (XSim)..."
cosim_design -rtl verilog -tool xsim -trace_level none
puts ">>> Co-Simulation done."

# =============================================================================
# Step 4 — Export IP for Vivado block design
# =============================================================================
puts ""
puts ">>> Step 4: Exporting IP..."
export_design \
    -format ip_catalog \
    -description "BitLinear HLS Accelerator — ternary int8 matvec" \
    -vendor "llmcore" \
    -library "hls" \
    -ipname "bitlinear_hls" \
    -version "1.0"

puts ""
puts ">>> HLS flow complete."
puts ">>> Synthesis report : $project_name/solution1/syn/report/"
puts ">>> Co-sim report    : $project_name/solution1/sim/report/"
puts ">>> Exported IP      : $project_name/solution1/impl/ip/"
