# =============================================================================
# run_hls_week5_vectors.tcl
# Vitis HLS — Week 5 (corrected): RTL co-simulation with Week 2 test vectors
# =============================================================================
# Usage (from fpga_erven/hls/bitlinear/):
#   /tools/Xilinx/2025.1/Vitis/bin/vitis-run --mode hls --tcl run_hls_week5_vectors.tcl
# =============================================================================

set project_name   "bitlinear_hls_project"
set top_function   "bitlinear_hls"
set part           "xczu7ev-ffvc1156-2-e"
set clock_period   "10"

# Compute absolute path to reference/test_vectors/
set tv_path [file normalize [file join [pwd] "../../../reference/test_vectors"]]
puts ">>> Test vector path: $tv_path"

if {![file isdirectory $tv_path]} {
    puts "ERROR: test_vectors directory not found at: $tv_path"
    puts "       Run this script from fpga_erven/hls/bitlinear/"
    exit 1
}

# =============================================================================
# Write TV_BASE_PATH to a generated header file
# -> avoids -mflags which is passed to make (not to the compiler) in 2025.1
# =============================================================================
set hdr_path [file join [pwd] "tv_path_generated.h"]
set hdr [open $hdr_path w]
puts $hdr "/* Auto-generated by run_hls_week5_vectors.tcl — do not edit */"
puts $hdr "#ifndef TV_PATH_GENERATED_H"
puts $hdr "#define TV_PATH_GENERATED_H"
puts $hdr "#define TV_BASE_PATH \"$tv_path\""
puts $hdr "#endif"
close $hdr
puts ">>> Generated: $hdr_path"

# =============================================================================
# Project setup
# =============================================================================
open_project -reset $project_name
set_top $top_function

add_files bitlinear_hls.cpp
add_files bitlinear_hls.h

add_files -tb testbench_cosim_vectors.cpp
add_files -tb tv_path_generated.h
add_files -tb ../packing/pack_ternary_2bit.cpp
add_files -tb ../packing/pack_ternary_2bit.h
add_files -tb ../packing/unpack_ternary_2bit.cpp

open_solution -reset "solution1"
set_part $part
create_clock -period $clock_period -name default

# =============================================================================
# Step 0: Synthesis
# =============================================================================
puts ">>> Step 0: Synthesis..."
csynth_design
puts ">>> Synthesis done. (II=1, Fmax 136.99 MHz expected)"

# =============================================================================
# Step 1: RTL Co-Simulation
# No -mflags needed — path is injected via tv_path_generated.h
# =============================================================================
puts ""
puts ">>> Step 1: RTL Co-Simulation with Week 2 binary test vectors..."
cosim_design -rtl verilog -tool xsim -trace_level none

puts ">>> Co-simulation done."

# =============================================================================
# Step 2: Export IP
# =============================================================================
puts ""
puts ">>> Step 2: Exporting IP..."
export_design \
    -format ip_catalog \
    -description "BitLinear HLS Accelerator — ternary int8 matvec" \
    -vendor "llmcore" \
    -library "hls" \
    -ipname "bitlinear_hls" \
    -version "1.0"

puts ""
puts ">>> Week 5 (vectors) complete."
puts ">>> Full chain: Python(S2) -> .bin -> C++ref -> HLS-csim(S3) -> RTL(S5) CLOSED"
