/* Auto-generated by run_hls_week5_vectors.tcl — do not edit */
#ifndef TV_PATH_GENERATED_H
#define TV_PATH_GENERATED_H
#define TV_BASE_PATH "/home/dllab/erven_workspace/llmcore-bitnet-accelerator-lab/reference/test_vectors"
#endif
